# Create Data of odd number

In [1]:
def ODD_NUMBERS(num):
    ODD = []
    for i in range(num):
        if i % 2 == 1:
            ODD.append(i)
    return ODD

num = 101

print("ODD Number: ",ODD_NUMBERS(num))

ODD Number:  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


# Split data into x and y

In [2]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [3]:
n_steps = 5
X, y = splitSequence(ODD_NUMBERS(num), n_steps = 5)

In [4]:
print(X)

[[ 1  3  5  7  9]
 [ 3  5  7  9 11]
 [ 5  7  9 11 13]
 [ 7  9 11 13 15]
 [ 9 11 13 15 17]
 [11 13 15 17 19]
 [13 15 17 19 21]
 [15 17 19 21 23]
 [17 19 21 23 25]
 [19 21 23 25 27]
 [21 23 25 27 29]
 [23 25 27 29 31]
 [25 27 29 31 33]
 [27 29 31 33 35]
 [29 31 33 35 37]
 [31 33 35 37 39]
 [33 35 37 39 41]
 [35 37 39 41 43]
 [37 39 41 43 45]
 [39 41 43 45 47]
 [41 43 45 47 49]
 [43 45 47 49 51]
 [45 47 49 51 53]
 [47 49 51 53 55]
 [49 51 53 55 57]
 [51 53 55 57 59]
 [53 55 57 59 61]
 [55 57 59 61 63]
 [57 59 61 63 65]
 [59 61 63 65 67]
 [61 63 65 67 69]
 [63 65 67 69 71]
 [65 67 69 71 73]
 [67 69 71 73 75]
 [69 71 73 75 77]
 [71 73 75 77 79]
 [73 75 77 79 81]
 [75 77 79 81 83]
 [77 79 81 83 85]
 [79 81 83 85 87]
 [81 83 85 87 89]
 [83 85 87 89 91]
 [85 87 89 91 93]
 [87 89 91 93 95]
 [89 91 93 95 97]]


In [5]:
X.shape

(45, 5)

In [6]:
print(y)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [7]:
for i in range(len(X)):
    print(X[i], y[i])

[1 3 5 7 9] 11
[ 3  5  7  9 11] 13
[ 5  7  9 11 13] 15
[ 7  9 11 13 15] 17
[ 9 11 13 15 17] 19
[11 13 15 17 19] 21
[13 15 17 19 21] 23
[15 17 19 21 23] 25
[17 19 21 23 25] 27
[19 21 23 25 27] 29
[21 23 25 27 29] 31
[23 25 27 29 31] 33
[25 27 29 31 33] 35
[27 29 31 33 35] 37
[29 31 33 35 37] 39
[31 33 35 37 39] 41
[33 35 37 39 41] 43
[35 37 39 41 43] 45
[37 39 41 43 45] 47
[39 41 43 45 47] 49
[41 43 45 47 49] 51
[43 45 47 49 51] 53
[45 47 49 51 53] 55
[47 49 51 53 55] 57
[49 51 53 55 57] 59
[51 53 55 57 59] 61
[53 55 57 59 61] 63
[55 57 59 61 63] 65
[57 59 61 63 65] 67
[59 61 63 65 67] 69
[61 63 65 67 69] 71
[63 65 67 69 71] 73
[65 67 69 71 73] 75
[67 69 71 73 75] 77
[69 71 73 75 77] 79
[71 73 75 77 79] 81
[73 75 77 79 81] 83
[75 77 79 81 83] 85
[77 79 81 83 85] 87
[79 81 83 85 87] 89
[81 83 85 87 89] 91
[83 85 87 89 91] 93
[85 87 89 91 93] 95
[87 89 91 93 95] 97
[89 91 93 95 97] 99


In [8]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [9]:
X

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]],

       [[ 5],
        [ 7],
        [ 9],
        [11],
        [13]],

       [[ 7],
        [ 9],
        [11],
        [13],
        [15]],

       [[ 9],
        [11],
        [13],
        [15],
        [17]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[13],
        [15],
        [17],
        [19],
        [21]],

       [[15],
        [17],
        [19],
        [21],
        [23]],

       [[17],
        [19],
        [21],
        [23],
        [25]],

       [[19],
        [21],
        [23],
        [25],
        [27]],

       [[21],
        [23],
        [25],
        [27],
        [29]],

       [[23],
        [25],
        [27],
        [29],
        [31]],

       [[25],
        [27],
        [29],
        [31],
        [33]],

       [[27],
        [29],
        [31],
        [33],
        

In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [11]:
model.layers

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 50)                10400     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [14]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
2/2 [==============================] - 1s 3ms/step - loss: 4715.8950 - accuracy: 0.0000e+00
Epoch 2/200
2/2 [==============================] - 0s 2ms/step - loss: 1904.0922 - accuracy: 0.0000e+00
Epoch 3/200
2/2 [==============================] - 0s 2ms/step - loss: 487.1256 - accuracy: 0.0000e+00
Epoch 4/200
2/2 [==============================] - 0s 3ms/step - loss: 198.0817 - accuracy: 0.0000e+00
Epoch 5/200
2/2 [==============================] - 0s 2ms/step - loss: 144.3089 - accuracy: 0.0000e+00
Epoch 6/200
2/2 [==============================] - 0s 2ms/step - loss: 268.5177 - accuracy: 0.0000e+00
Epoch 7/200
2/2 [==============================] - 0s 2ms/step - loss: 121.3513 - accuracy: 0.0000e+00
Epoch 8/200
2/2 [==============================] - 0s 2ms/step - loss: 18.0929 - accuracy: 0.0000e+00
Epoch 9/200
2/2 [==============================] - 0s 3ms/step - loss: 71.1294 - accuracy: 0.0000e+00
Epoch 10/200
2/2 [==============================] - 0s 2ms/step - loss: 7

2/2 [==============================] - 0s 998us/step - loss: 0.0094 - accuracy: 0.0000e+00
Epoch 82/200
2/2 [==============================] - 0s 3ms/step - loss: 0.0090 - accuracy: 0.0000e+00
Epoch 83/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0086 - accuracy: 0.0000e+00
Epoch 84/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0086 - accuracy: 0.0000e+00
Epoch 85/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0084 - accuracy: 0.0000e+00
Epoch 86/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.0000e+00
Epoch 87/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0082 - accuracy: 0.0000e+00
Epoch 88/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0082 - accuracy: 0.0000e+00
Epoch 89/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.0000e+00
Epoch 90/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.

2/2 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 0.0000e+00
Epoch 161/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 0.0000e+00
Epoch 162/200
2/2 [==============================] - 0s 3ms/step - loss: 0.0037 - accuracy: 0.0000e+00
Epoch 163/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.0000e+00
Epoch 164/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.0000e+00
Epoch 165/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 0.0000e+00
Epoch 166/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 0.0000e+00
Epoch 167/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.0000e+00
Epoch 168/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 0.0000e+00
Epoch 169/200
2/2 [==============================] - 0s 2ms/step - loss: 0.0035 - accur

In [15]:
test_data = np.array([1, 3, 5, 7, 9])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[1],
        [3],
        [5],
        [7],
        [9]]])

In [16]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 151ms/step
[[10.889459]]


In [17]:
test_data = np.array([89, 91, 93, 95, 97])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[89],
        [91],
        [93],
        [95],
        [97]]])

In [18]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 19ms/step
[[99.01007]]
